name: Terraform CI/CD

on:
  push:
    branches:
      - main
      - master

permissions:
  contents: read    
  id-token: write   
  pull-requests: write

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      # Step 3: Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

       # Step 4: Initialize Terraform
      - name: Terraform Init
        run: terraform init
     
      # Step 5: Validate Terraform
      - name: Terraform Validate
        run: terraform validate

      # Step 6: Install Checkov
      - name: Install Checkov
        run: |
          pip install checkov

      # Step 7: Run Checkov on Terraform files
      - name: Checkov Scan
        run: |
          checkov -d . --skip-check CKV_AWS_79,CKV_AWS_126,CKV_AWS_8,CKV_AWS_135,CKV2_AWS_41

      # Step 8: Plan Terraform changes
      - name: Terraform Plan
        run: terraform plan

      # Step 9: Apply Terraform changes
      - name: Terraform Apply
        run: terraform apply --auto-approve
